//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Id_Contacto { get; set; }
        public int Id_Empresa { get; set; }
        public string Nombre { get; set; }
        public string CUI { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Notificar { get; set; }
        public string Estado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
