//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleIngresoProveedor
    {
        public int Id_DetalleIngresoProveedor { get; set; }
        public int Id_IngresoProveedor { get; set; }
        public string CodigoDetalle { get; set; }
        public string Detalle_Rechazo { get; set; }
        public Nullable<System.TimeSpan> Hora_Entrega { get; set; }
        public string Estado_Entrega { get; set; }
    
        public virtual IngresoProveedor IngresoProveedor { get; set; }
    }
}
