//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HorarioEntrega : BaseVM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioEntrega()
        {
            this.IngresoProveedor = new HashSet<IngresoProveedor>();
        }
    
        public int Id_HorarioEntrega { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Hora de entrega")]
        [Required(ErrorMessage = "Debe ingresar la hora entrega")]
        public Nullable<System.TimeSpan> Hora_Entrega { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Hora de salida")]
        [Required(ErrorMessage = "Debe ingresar la hora salida")]
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }

        [DefaultValue("Activo")]
        [StringLength(8, MinimumLength = 6)]
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoProveedor> IngresoProveedor { get; set; }
    }
}
