//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingreso()
        {
            this.Mensajero = new HashSet<Mensajero>();
            this.RutaEntrega = new HashSet<RutaEntrega>();
        }
    
        public int Id_Ingreso { get; set; }
        public string Codigo_Ingreso { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Proveedor { get; set; }
        public Nullable<int> No_Paquetes { get; set; }
        public string Nombre_Mensajero { get; set; }
        public string CUI_Mensajero { get; set; }
        public string Detalle_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajero> Mensajero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaEntrega> RutaEntrega { get; set; }
    }
}
