//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajero
    {
        public int Id_Mensajero { get; set; }
        public Nullable<int> Id_Ingreso { get; set; }
        public string Orden { get; set; }
        public string Tipo_Ingreso { get; set; }
        public string Nombre { get; set; }
        public string CUI { get; set; }
        public string Carnet { get; set; }
    
        public virtual Ingreso Ingreso { get; set; }
    }
}
