//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTS_MensajeriaEntities : DbContext
    {
        public RTS_MensajeriaEntities()
            : base("name=RTS_MensajeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<DetalleIngresoProveedor> DetalleIngresoProveedor { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<HorarioEntrega> HorarioEntrega { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<IngresoProveedor> IngresoProveedor { get; set; }
        public virtual DbSet<Mensajero> Mensajero { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<RutaEntrega> RutaEntrega { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
